name: Deploy Laravel ke Jagoan Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, bcmath, xml, curl, zip, intl, pdo, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Copy project to server (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 45022
          source: "."
          target: "gongkomo/repositories/be-gongkomodotour"

      - name: Run post-deploy script on server (via SSH)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 45022
          script: |
            rm -rf /home/${{ secrets.SSH_USER }}/api.gongkomodotour.com/*
            cp -r /home/${{ secrets.SSH_USER }}/repositories/be-gongkomodotour/* /home/${{ secrets.SSH_USER }}/api.gongkomodotour.com/
            cd /home/${{ secrets.SSH_USER }}/api.gongkomodotour.com/
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan storage:link
